# Generated by Django 4.2 on 2023-05-24 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('idactividad', models.AutoField(db_column='idActividad', primary_key=True, serialize=False)),
                ('semana', models.IntegerField()),
                ('nombre', models.CharField(max_length=45)),
                ('fecha', models.DateTimeField()),
                ('fechaPublicacion', models.DateTimeField()),
                ('diasrecordatorios', models.IntegerField(db_column='diasRecordatorios')),
                ('esvirtual', models.BooleanField(db_column='esVirtual')),
                ('enlace', models.CharField(blank=True, max_length=100, null=True)),
                ('afiche', models.ImageField(upload_to='dist/images/afiches/')),
                ('enlaceevidencia', models.CharField(blank=True, max_length=200, null=True)),
                ('observacion', models.CharField(blank=True, max_length=300, null=True)),
                ('fedicion', models.DateTimeField(blank=True, null=True)),
                ('editor', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Actividad',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Asistenteadministrativo',
            fields=[
                ('idasistente', models.AutoField(db_column='idAsistente', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido1', models.CharField(max_length=45)),
                ('apellido2', models.CharField(max_length=45)),
                ('auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'AsistenteAdministrativo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('idlistadocentes', models.AutoField(db_column='idListaDocentes', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Docentes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estadoactividad',
            fields=[
                ('idestado', models.AutoField(db_column='idEstado', primary_key=True, serialize=False)),
                ('desestado', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'EstadoActividad',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Plantrabajo',
            fields=[
                ('semestre', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('semanainicial', models.DateField(db_column='semanaInicial')),
                ('semanafinal', models.DateField()),
                ('actividades', models.ManyToManyField(db_table='ActividadesPlanTrabajo', to='base.actividad')),
            ],
            options={
                'db_table': 'PlanTrabajo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idrol', models.AutoField(db_column='idRol', primary_key=True, serialize=False)),
                ('desrol', models.CharField(db_column='desRol', max_length=45)),
            ],
            options={
                'db_table': 'Rol',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('idsede', models.AutoField(db_column='idSede', primary_key=True, serialize=False)),
                ('codigosede', models.CharField(db_column='codigoSede', max_length=2)),
            ],
            options={
                'db_table': 'Sede',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tipoactividad',
            fields=[
                ('idtipoactividad', models.AutoField(db_column='idTipoActividad', primary_key=True, serialize=False)),
                ('destipoactividad', models.CharField(db_column='desTipoActividad', max_length=45)),
            ],
            options={
                'db_table': 'TipoActividad',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Semanasvacaciones',
            fields=[
                ('idsemanasvacaciones', models.AutoField(db_column='idSemanasVacaciones', primary_key=True, serialize=False)),
                ('semanavacacional', models.DateField(db_column='semanaVacacional')),
                ('semestre', models.ForeignKey(db_column='idPlanTrabajo', on_delete=django.db.models.deletion.DO_NOTHING, to='base.plantrabajo')),
            ],
            options={
                'db_table': 'SemanasVacaciones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('codigo', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('numprofesor', models.IntegerField(db_column='numprofesor')),
                ('nombre', models.CharField(max_length=45)),
                ('apellido1', models.CharField(max_length=45)),
                ('apellido2', models.CharField(max_length=45)),
                ('oficina', models.CharField(max_length=45)),
                ('teloficina', models.IntegerField(db_column='telOficina')),
                ('telcelular', models.IntegerField(db_column='telCelular')),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='profes/')),
                ('fcreacion', models.DateTimeField()),
                ('fedicion', models.DateTimeField(blank=True, null=True)),
                ('auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idsede', models.ForeignKey(db_column='sede', on_delete=django.db.models.deletion.DO_NOTHING, to='base.sede')),
            ],
            options={
                'db_table': 'Profesor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FotoProfesor',
            fields=[
                ('idfoto', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(upload_to='fotos/')),
                ('idprofesor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.profesor')),
            ],
            options={
                'db_table': 'FotoProfesor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Evidencias',
            fields=[
                ('idevidencia', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='dist/images/evidencias/')),
                ('idactividad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.actividad')),
            ],
            options={
                'db_table': 'Evidencias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('carnet', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('nombreadicional', models.CharField(db_column='nombreAdicional', max_length=45)),
                ('apellido1', models.CharField(max_length=45)),
                ('apellido2', models.CharField(max_length=45)),
                ('telefono', models.IntegerField(null=True)),
                ('correotec', models.CharField(db_column='correoTec', max_length=50)),
                ('fedicion', models.DateTimeField(blank=True, null=True)),
                ('editor', models.CharField(blank=True, max_length=120, null=True)),
                ('fcreacion', models.DateTimeField()),
                ('sede', models.ForeignKey(db_column='sede', on_delete=django.db.models.deletion.DO_NOTHING, to='base.sede')),
            ],
            options={
                'db_table': 'Estudiante',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Equipotrabajo',
            fields=[
                ('idequipotrabajo', models.AutoField(db_column='idEquipoTrabajo', primary_key=True, serialize=False)),
                ('fedicion', models.DateTimeField(blank=True, null=True)),
                ('docentes', models.ManyToManyField(through='base.Docentes', to='base.profesor')),
                ('editor', models.ForeignKey(db_column='idEditor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.asistenteadministrativo')),
            ],
            options={
                'db_table': 'EquipoTrabajo',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='docentes',
            name='idequipotrabajo',
            field=models.ForeignKey(db_column='idEquipoTrabajo', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.equipotrabajo'),
        ),
        migrations.AddField(
            model_name='docentes',
            name='idprofesor',
            field=models.ForeignKey(db_column='idProfesor', on_delete=django.db.models.deletion.DO_NOTHING, to='base.profesor'),
        ),
        migrations.AddField(
            model_name='docentes',
            name='rol',
            field=models.ForeignKey(db_column='rol', on_delete=django.db.models.deletion.DO_NOTHING, to='base.rol'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('idcomentario', models.AutoField(db_column='idComentario', primary_key=True, serialize=False)),
                ('contenido', models.CharField(max_length=250)),
                ('fecha', models.DateTimeField()),
                ('actividad', models.ForeignKey(db_column='actividad', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.actividad')),
                ('autor', models.ForeignKey(db_column='autor', on_delete=django.db.models.deletion.DO_NOTHING, to='base.profesor')),
            ],
            options={
                'db_table': 'Comentario',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='asistenteadministrativo',
            name='sede',
            field=models.ForeignKey(db_column='sede', on_delete=django.db.models.deletion.DO_NOTHING, to='base.sede'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='estado',
            field=models.ForeignKey(db_column='estado', on_delete=django.db.models.deletion.DO_NOTHING, to='base.estadoactividad'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='planTrabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.plantrabajo'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='responsables',
            field=models.ManyToManyField(db_table='Responsable', to='base.profesor'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='tipo',
            field=models.ForeignKey(db_column='tipo', on_delete=django.db.models.deletion.DO_NOTHING, to='base.tipoactividad'),
        ),
    ]
